### PR TITLE
fix: gtag script error

### PR DESCRIPTION
**Pull request by ZacksTsang**

### CODE REVIEW

**Comment by ZacksTsang** [comment]
@chenshuai2144 can you help to merge this?

**Comment by cctv2206** [comment]
I run into this bug just now
fix looks great

**Comment by rayronvictor** [comment]
Since Google will drop support for Google Analytics Universal on July 2023, I believe this PR is very important for people that are upgrading from Universal to GA4.

cc: @sorrycc @kuitos

**Comment by rayronvictor** [comment]
Hey @chenshuai2144 @xiaohuoni, this fix is very important as Google Analytics Universal will stop in 2 months and GA4 isn't working yet.

@ZacksTsang is the author from previous PR that added GA4.

This PR is a simple variable name correction. Easy to review.

**Review by xiaohuoni — APPROVED** [review]

**Review by sorrycc — CHANGES_REQUESTED** [review]
Please do not modify the version number and Changelog, these will be done automatically through scripts.

**Comment by ZacksTsang** [comment]
@sorrycc done

**Review by sorrycc — APPROVED** [review]

**Comment by ineo6** [comment]
Version was not changed and did not publish to npm ?

**Pull request merged**
